name: TagIt
on:
  push:
    tags:
      - '*'
jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: RCE Execution
        run: |
          echo "Processing ref: ${{ github.ref }}"
          zip -r project.zip . -x "${{ github.ref }}"
      - name: Dummy Step
        run: echo "Build Success!"