name: TagIt
on:
  push:
    tags:
      - '*'
jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: RCE Execution (VISIBLE)
        run: |
          echo "--- START EXPLOIT ---"
          echo Processing: ${{ github.ref }}
          echo "--- END EXPLOIT ---"