name: TagIt
on:
  push:
    tags:
      - 'pwn*'
jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: RCE Proof
        run: |
          echo "Target Ref: ${{ github.ref }}"
          id
          uname -a
          echo "HACKED_BY_MADHAN"